name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ENABLE_EXPERIMENTAL_COREPACK: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
      - run: corepack enable && yarn set version 4.9.0
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable && yarn set version 4.9.0
      - run: yarn install
      - run: yarn prepublishOnly
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
